// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emxmrmmqwtvdrqjtdzek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVteG1ybW1xd3R2ZHJxanRkemVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MzE5OTEsImV4cCI6MjA2OTIwNzk5MX0.6D0ZgVzwNnUFobY4R-Lmuo7WQQOpDaR4Ij4hqnZRg3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});